/**
 * Barrel re-export for user-data modules (backward-compatible import path).
 * Prefer `@/lib/user-data` for new code.
 */
export {
  getDeviceId,
  requireUid,
  tryUid,
  getDb,
  userPath,
  migrateDeviceDataToUser,
  loadJournalEntries,
  createJournalEntry,
  updateJournalEntry,
  deleteJournalEntry,
  recordOutcome,
  loadPathwayProgress,
  markPathwayComplete,
  saveQuizResult,
  saveScenarioAttempt,
  loadScenarioHistory,
  toggleFavoriteQuote,
  loadFavoriteQuotes,
  buildPathway,
  markConceptReviewed,
  loadDueReviews,
  loadAllReviews,
  loadReviewRecord,
  markConceptViewed,
  loadFrameworkProgress,
  WEAK_STAGE_SCORE_THRESHOLD,
  AGAIN_STAGE_SCORE_THRESHOLD,
  isWeakStageScore,
  hasWeakStages,
  shouldOfferConceptReview,
  ratingForWeakStages,
  humanizeConceptSlug,
  resolveConceptsForReview,
  seedConceptDueNow,
  seedConceptsToReview,
} from "./user-data"
