// Static fallback data for GitHub Pages demo
// When the backend API is unavailable, pages fall back to this data

export const staticFrameworks = [
  { id: "11111111-1111-1111-1111-111111111111", slug: "strategic-decision-making", title: "Strategic Decision-Making", description: "Core frameworks for making high-stakes decisions under uncertainty", category: "decision-making", difficulty: 2, estimated_time_minutes: 45 },
  { id: "22222222-2222-2222-2222-222222222222", slug: "financial-mastery", title: "Financial Mastery", description: "Read financial statements, value companies, allocate capital like a CEO", category: "financial", difficulty: 3, estimated_time_minutes: 60 },
  { id: "33333333-3333-3333-3333-333333333333", slug: "competitive-market-analysis", title: "Competitive & Market Analysis", description: "Frameworks for understanding markets, competition, and positioning", category: "strategy", difficulty: 2, estimated_time_minutes: 45 },
  { id: "44444444-4444-4444-4444-444444444444", slug: "organizational-people", title: "Organizational & People", description: "Structure teams, develop talent, build culture, and lead through change", category: "org", difficulty: 3, estimated_time_minutes: 60 },
  { id: "55555555-5555-5555-5555-555555555555", slug: "engineering-product-leadership", title: "Engineering & Product Leadership", description: "Build the right things right with DORA metrics, agile delivery, and technical strategy", category: "engineering", difficulty: 4, estimated_time_minutes: 75 },
  { id: "66666666-6666-6666-6666-666666666666", slug: "risk-governance-crisis", title: "Risk, Governance & Crisis", description: "Manage enterprise risk, govern as a board member, and lead through crisis", category: "risk", difficulty: 4, estimated_time_minutes: 60 },
  { id: "77777777-7777-7777-7777-777777777777", slug: "cause-analysis-methods", title: "Cause Analysis Methods", description: "Diagnose root causes with 11 methods from 5 Whys to Causal Inference", category: "analysis", difficulty: 3, estimated_time_minutes: 45 },
  { id: "88888888-8888-8888-8888-888888888888", slug: "negotiation-deal-making", title: "Negotiation & Deal-Making", description: "Master the art of getting to yes: from BATNA to integrative bargaining", category: "negotiation", difficulty: 3, estimated_time_minutes: 60 },
  { id: "99999999-9999-9999-9999-999999999999", slug: "innovation-rd-management", title: "Innovation & R&D Management", description: "Turn ideas into growth: from disruptive innovation to lean experimentation", category: "innovation", difficulty: 3, estimated_time_minutes: 45 },
  { id: "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000001", slug: "business-model-strategy", title: "Business Model & Strategy Design", description: "Design, analyze, and evolve your business model with proven strategic frameworks", category: "strategy", difficulty: 2, estimated_time_minutes: 45 },
  { id: "bbbbbbbb-bbbb-bbbb-bbbb-bbbb00000001", slug: "operations-quality-management", title: "Operations & Quality Management", description: "Drive operational excellence through lean, quality, and constraint management", category: "operations", difficulty: 3, estimated_time_minutes: 45 },
  { id: "cc000001-0000-4000-8000-000000000001", slug: "decision-tree-analysis", title: "Decision Tree Analysis", description: "Map decisions as branching paths with probabilities and payoffs", category: "analysis", difficulty: 2, estimated_time_minutes: 30 },
  { id: "cc000001-0000-4000-8000-000000000002", slug: "sensitivity-analysis", title: "Sensitivity Analysis", description: "Stress-test your assumptions: find which variables most affect outcomes", category: "analysis", difficulty: 2, estimated_time_minutes: 30 },
  { id: "cc000001-0000-4000-8000-000000000003", slug: "stakeholder-analysis", title: "Stakeholder Analysis & Mapping", description: "Identify who has power over your outcome and how to engage them", category: "analysis", difficulty: 2, estimated_time_minutes: 25 },
  { id: "cc000001-0000-4000-8000-000000000004", slug: "cohort-analysis", title: "Cohort Analysis", description: "Group customers by when they joined and track behavior over time", category: "analysis", difficulty: 2, estimated_time_minutes: 25 },
  { id: "dd000001-0000-4000-8000-000000000001", slug: "cognitive-biases-debiasing", title: "Cognitive Biases & Debiasing", description: "Identify and counteract the 25+ cognitive biases that warp CEO judgment", category: "decision-making", difficulty: 2, estimated_time_minutes: 45 },
  { id: "dd000001-0000-4000-8000-000000000002", slug: "multi-criteria-decision-analysis", title: "Multi-Criteria Decision Analysis", description: "Structured scoring and weighting when you have 5+ options and 10+ criteria", category: "decision-making", difficulty: 2, estimated_time_minutes: 35 },
  { id: "dd000001-0000-4000-8000-000000000003", slug: "decision-quality-framework", title: "Decision Quality Framework", description: "Spetzler's 6-element framework for auditing major decisions", category: "decision-making", difficulty: 3, estimated_time_minutes: 35 },
  { id: "dd000001-0000-4000-8000-000000000004", slug: "intuition-vs-analysis", title: "Intuition vs Analysis", description: "Know when to rely on instinct vs structured analysis", category: "decision-making", difficulty: 2, estimated_time_minutes: 25 },
  { id: "dd000001-0000-4000-8000-000000000005", slug: "decision-speed-velocity", title: "Decision Speed & Velocity", description: "Know when to decide fast vs slow and build high-velocity organizations", category: "decision-making", difficulty: 2, estimated_time_minutes: 25 },
  { id: "dd000001-0000-4000-8000-000000000006", slug: "red-teaming-wargaming", title: "Red Teaming & Wargaming", description: "Simulate your opponent's best counter-move before they do it", category: "decision-making", difficulty: 3, estimated_time_minutes: 30 },
]

export const staticScenarios: Array<{ id: string; slug: string; title: string; description: string; framework_id: string; difficulty: number }> = [
  { id: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa", slug: "pricing-war-response", title: "Pricing War Response", description: "A competitor launches a free tier matching your core features. You have 2 weeks before the board meeting.", framework_id: "33333333", difficulty: 3 },
  { id: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb", slug: "acquisition-target-evaluation", title: "Acquisition Target Evaluation", description: "Evaluate a $15M acquisition target. Board needs your recommendation in 1 week.", framework_id: "22222222", difficulty: 4 },
  { id: "cccccccc-cccc-cccc-cccc-cccccccccccc", slug: "crisis-major-security-incident", title: "Crisis: Major Security Incident", description: "Data breach affecting 10,000 customers. Regulators, customers, board all need communication.", framework_id: "11111111", difficulty: 5 },
  { id: "dddddddd-dddd-dddd-dddd-dddddddddddd", slug: "scaling-org-from-50-to-200", title: "Scaling Org from 50 to 200", description: "Your startup raised Series B. You need to double the team in 6 months.", framework_id: "44444444", difficulty: 3 },
  { id: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee", slug: "platform-vs-feature-investment", title: "Platform vs Feature Investment", description: "CTO wants 6 months for platform rewrite. VP Product wants 3 new features.", framework_id: "55555555", difficulty: 4 },
  { id: "ffffffff-ffff-ffff-ffff-ffffffffffff", slug: "root-cause-customer-churn-spike", title: "Root Cause: Customer Churn Spike", description: "Monthly churn doubled from 3% to 6% in 30 days. Find the root cause.", framework_id: "77777777", difficulty: 3 },
]